export const SUBJECTS = {
  VOCABULARY: 'VOCABULARY',
  GRAMMAR: 'GRAMMAR',
  READING_PRACTICE: 'READING_PRACTICE',
  KANJI: 'KANJI',
  LISTENING: 'LISTENING',
  READING: 'READING',
};

export default {
  SUBJECTS: SUBJECTS,
};
