export const SUBJECTS = {
  VOCABULARY: 'VOCABULARY',
  GRAMMAR: 'GRAMMAR',
  KANJI: 'KANJI',
  LISTENING: 'LISTENING',
  READING: 'READING',
  READING_PRACTICE: 'READING_PRACTICE',
  CONVERSATION: 'CONVERSATION',
  EXERCISE: 'EXERCISE',
  EXAMINATION: 'EXAMINATION',
  REFERENCE: 'REFERENCE',
};

export default {
  SUBJECTS: SUBJECTS,
};
